nodeLinker: node-modules

packageExtensions:
  "@typescript-eslint/eslint-plugin@*":
    peerDependenciesMeta:
      "@types/typescript":
        optional: true
      "@types/typescript-eslint__parser":
        optional: true
  "eslint-config-standard@*":
    peerDependenciesMeta:
      "@types/eslint-plugin-import":
        optional: true
      "@types/eslint-plugin-n":
        optional: true
      "@types/eslint-plugin-promise":
        optional: true
  "eslint-plugin-prettier@*":
    peerDependenciesMeta:
      "@types/eslint-config-prettier":
        optional: true
  "ts-jest@*":
    peerDependenciesMeta:
      "@types/babel-jest":
        optional: true
      "@types/esbuild":
        optional: true
      "@types/jest-util":
        optional: true
      "@types/jest__transform":
        optional: true
      "@types/jest__types":
        optional: true
  "ts-node@*":
    peerDependenciesMeta:
      "@types/swc__core":
        optional: true
      "@types/swc__wasm":
        optional: true
